import type { Metadata } from "next";
import "./globals.css";
import { ViewportLayout } from "next/dist/lib/metadata/types/extra-types";
import ThemeRegistry from "@/src/ThemeRegistry/ThemeRegistry";
import VConsoleWarper from "@/src/VConsoleWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: ViewportLayout = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  interactiveWidget: "resizes-content",
  userScalable: false,
  viewportFit: "cover",
}



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <ThemeRegistry>
          {children}
          <VConsoleWarper />
        </ThemeRegistry>
      </body>
    </html>
  );
}
